### PR TITLE
Add restaurant profile and card to fit with demo script

### PR DESCRIPTION
**Pull request by Mihobsine**
Related to [SPRO-161]

[SPRO-161]: https://shokuapp.atlassian.net/browse/SPRO-161

### CODE REVIEW

**Comment by anthoninCL** [comment]
When generating the allergen notebook, we cannot see the "Entrecôte" dish so I don't think the allergen notebook triggers the right card.

**Comment by anthoninCL** [comment]
Looking at the sauce in the Entrecôte dish, I can see that there is "Farine de blé" so it does not fit with the profile we're using in the demo.

**Review by anthoninCL — COMMENTED** [review]
I have nothing to say on the code itself, just the datas showed in the app, but because I do not let any comment on the code, I cannot Request Changes, so I'm just commenting.

**Comment by Mihobsine** [comment]
All problems point out by previous comments are now fixed.

**Review by anthoninCL — COMMENTED** [review]
I don't know if you agree with @Matttx but I think the allergen notebook is quite small for the demo, because the card only have 9 dishes.

**Comment by Mihobsine** [comment]
The allergen notebook look less empty now

**Review by Matttx — APPROVED** [review]

**Review by anthoninCL — APPROVED** [review]

**Pull request merged**
